# -*- coding: utf-8 -*-
"""Practica_Parentesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xuym66LQk8ZsvHf0byX_kok81dfWuMwf
"""

# Programacion
# Practica 1
# Lopez Morales Ricardo Enrique
# Zuniga Soto Saul

alfabeto = ['(',')']

def parent(cadena):
  '''esta funcion detecta si una cadena de parentesis esta bien formada o no,
  primero filtra los caracteres externos, luego casos donde se inicia con
  parentesis cerrado, luego casos donde se finaliza con un parentesis abierto
  y al final con una comprobacion de si cada parentesis tiene un
  correspondiente'''

  #1 Filtra caracteres externos
  #2 Hace la correspondencia entre parentesis
  #3 Filtra si se inicio con parentesis cerrado
  #4 Filtra si se termina con un parentesis abierto
  Bool1 = True
  Bool2 = True
  Bool3 = True
  Bool4 = True

  Pila = [cadena]

  for i in cadena:
    if i not in alfabeto:
      Bool1 = False

  if Bool1 == True:
    if cadena[0] == alfabeto[1]:
      Bool3 = False
      Bool2 = False
    elif cadena[-1] == alfabeto[0]:
      Bool4 = False
    elif cadena[0] == alfabeto[0]:
      Bool3 = True
      for i in (cadena):
        if i == alfabeto[0] and len(Pila) >= 1:
          Pila.append('A')
        elif i == alfabeto[0]:
          Bool2 == False
        elif i == alfabeto[1] and len(Pila) >= 1:
          Pila.pop()
        elif i == alfabeto[1]:
          Bool2 == False


  if Bool1 == False:
    print('Se han colocado uno o mas caracteres que no son parentesis')
    print('Cadena mal formada')

  elif Bool3 == False:
    print('Se ha iniciado la cadena con un parentesis cerrado')
    print('Cadena mal formada')

  elif Bool4 == False:
    print('El ultimo caracter de la cadena es un parentesis abierto')
    print('Cadena mal formada')

  elif len(Pila) == 1:
    Bool2 = True
  else:
    Bool2 = False
    print('Existe uno o mas parentesis sin su correspondiente')
    print('Cadena mal formada')

  if Bool1 == True and Bool2 == True and Bool3 == True and Bool4 == True:
    print('Cadena bien formada')

  return

if __name__ ==  '__main__' :
  cadena = input("Introduzca una cadena unicamente formada por parentesis: ")
  parent(cadena)