# -*- coding: utf-8 -*-
"""Proyecto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5TIwi9C_w-gIm291W3fKrSYCwuscNHM
"""

!pip install criticalpath
from criticalpath import Node

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

class LeerArchivo:
  def lect(self):
    arch= pd.read_excel('/content/drive/MyDrive/Creacion_de_la_carrera_de_mat_ap.xlsx')
    Act = arch['Actividad']
    Dur = arch['Duracion']
Archivo = LeerArchivo()
Archivo.lect()

class Critico:
  def graf(self):
    p = Node("Proyecto")

    A = p.add(Node("1", duration=3))
    B = p.add(Node("2", duration=15))
    C = p.add(Node("3", duration=10))
    D = p.add(Node("4", duration=2))
    E = p.add(Node("5", duration=8))
    F = p.add(Node("6", duration=10))
    G = p.add(Node("7", duration=10))
    H = p.add(Node("8", duration=8))
    I = p.add(Node("9", duration=5))
    J = p.add(Node("10", duration=20))
    K = p.add(Node("11", duration=10))
    L = p.add(Node("12", duration=8))
    M = p.add(Node("13", duration=6))
    N = p.add(Node("14", duration=10))
    O = p.add(Node("15", duration=20))
    P = p.add(Node("16", duration=15))
    Q = p.add(Node("17", duration=10))
    R = p.add(Node("18", duration=3))
    S = p.add(Node("19", duration=8))
    T = p.add(Node("20", duration=8))
    U = p.add(Node("21", duration=8))

    p.link(A,B).link(B,C).link(C,D).link(D,E).link(D,F).link(D,G).link(D,H).link(D,I).link(E,J).link(F,K).link(G,L).link(H,M).link(K,N).link(J,O).link(N,O).link(L,P).link(M,P).link(R,P).link(D,Q).link(P,Q).link(O,R).link(R,S).link(Q,T).link(S,T).link(T,U)
    p.update_all()

    D = p.duration
    C = p.get_critical_path()

    print(C)
    print(D)

Reporte = Critico()
Reporte.graf()

class Txt:
  def wrt(self):
    Reporte = open('/content/drive/MyDrive/Datos.txt' , "w")
    Reporte.write(str("El tiempo necesario para la elaboracion del proyecto es de 124 semanas" + "\n"))
    Reporte.write(str("Las actividades criticas son:"+ "\n"))
    Reporte.write(str("1"+ "\n"))
    Reporte.write(str("2"+ "\n"))
    Reporte.write(str("3"+ "\n"))
    Reporte.write(str("4"+ "\n"))
    Reporte.write(str("6"+ "\n"))
    Reporte.write(str("11"+ "\n"))
    Reporte.write(str("14"+ "\n"))
    Reporte.write(str("15"+ "\n"))
    Reporte.write(str("18"+ "\n"))
    Reporte.write(str("16"+ "\n"))
    Reporte.write(str("17"+ "\n"))
    Reporte.write(str("20"+ "\n"))
    Reporte.write(str("21"+ "\n"))

    Reporte.close()

Rep = Txt()
Rep.wrt()

